
- name: Run anomaly injection docker container
  tags: [ docker, injector ]
  docker_container:
    name: "{{ injector.container_name }}"
    image: alexanderacker/anomaly_injector
    pull: true
    ports:
      - "{{ injector.api_port }}:{{ injector.api_port }}"
    network_mode: host
    pid_mode: host
    privileged: yes
    command: >
      -host "{{ injector.hostname }}"
      -api-port {{ injector.api_port }}
      -collector-host "{{ ansible_default_ipv4.address }}"
      -collector-port {{ collector.api_port }}
      -set-collector-tags {{ injector.set_collector_tags }}
