- name: Check container status
  shell: docker inspect --format='{{ '{{' }} .State.Status {{ '}}' }}' {{ container }}
  register: result

- debug: var=result.stdout  

- name: Start if not running
  shell: docker start {{ container }}
  when: "'running' not in result.stdout"
