#!/usr/bin/env ansible-playbook

- import_playbook: playbook-base.yml

- name: Install the load generation client
  hosts: client
  tags: [ docker, client ]
  tasks:
    - name: Run video load generation client docker container
      become: true
      docker_container:
        name: rtmp-client
        image: antongulenko/stream-statistics-client
        pull: true
        command: |
            -n 0
            -o {{ rtmp.client_log_dir_mounted }}/{{ rtmp.client_log_file }}
            -o :{{ rtmp.client_data_port }}
            -api :{{ rtmp.client_api_port }}
            -files-buf 8
            -files-check-output 2s
            {% for host in groups['load-balancer'] %}
            rtmp://{{ hostvars[host]['private_ip'] }}:{{ rtmp.port }}{{ rtmp.default_request_path }}
            {% endfor %}
        volumes:
          - "{{ rtmp.client_log_dir }}:{{ rtmp.client_log_dir_mounted }}"
        ports:
          - "{{ rtmp.client_data_port }}:{{ rtmp.client_data_port }}"
          - "{{ rtmp.client_api_port }}:{{ rtmp.client_api_port }}"

- name: Install the backend video server
  hosts: backend
  tags: [ docker, backend ]
  tasks:
    - name: Run backend video server docker container
      become: true
      docker_container:
        name: rtmp-server
        image: antongulenko/rtmp-nginx-server
        pull: true
        ports:
          # The container ports are hardcoded because they cannot be configured
          - "{{ rtmp.backend_http_port }}:8080"
          - "{{ rtmp.port }}:1935"

- name: Install the load balancer
  hosts: load-balancer
  tags: [ docker, load-balancer ]
  tasks:
    - name: Run load balancer docker container
      become: true
      docker_container:
        name: rtmp-balancer
        image: antongulenko/rtmp-haproxy-balancer
        pull: true
        volumes:
          - "/dev/log:/dev/log"
        ports:
          - "{{ rtmp.port }}:{{ rtmp.port }}"
          - "{{ rtmp.balancer_stats_port }}:{{ rtmp.balancer_stats_port }}"
        env:
          RTMP_PORT: "{{ rtmp.port }}"
          STATS_PORT: "{{ rtmp.balancer_stats_port }}"
          RTMP_SERVERS: "{{ groups['backend'] | map('extract', hostvars, ['private_ip']) | join(' ') }}"
