#!/usr/bin/env ansible-playbook

- import_playbook: reset-collector-injector.yml

- name: Delete collector data
  hosts: all:!client
  vars:
    cleaned_directory: "{{ collector.data_path }}"
  tasks:
    - include_tasks: ../../Common/Ansible/clean-directory-contents-tasks.yml

- name: Delete client statistics data
  hosts: client
  vars:
    cleaned_directory: "{{ rtmp.client_log_dir }}"
  tasks:
    - include_tasks: ../../Common/Ansible/clean-directory-contents-tasks.yml
